#!/usr/bin/env bash
# displays numbers from 1 to 100
a=1;
while [[ $a -lt 101 ]]; do
if [ $((a%15)) = 0 ]                                                                                                                                   

then                                                                                                                                                     

	echo "FizzBuzz"	
elif [ $((a%3)) = 0 ]
then
echo "Fizz"
elif [ $((a%5)) = 0 ]
then
echo "Buzz"
else
echo "$a"
fi
a=$((a+1));
done
