#!/usr/bin/env bash
#The script creates the file "myscript.pid" with its PID then displays "to infinity and beyond" indefinitely, displays a message when receiving the SIGTERM and SIGINT signals then deletes myscript.pid

echo $$ > /var/run/myscript.pid

trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!";' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT

while true; do
  echo "To infinity and beyond"
  sleep 1
done 
