#!/usr/bin/env bash
# The script manages daemons according to certain conditions

case "$1" in
    start)
        ./manage_my_process &
        process_id=$!
        echo "$process_id" > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        process_id=$(cat /var/run/my_process.pid)
        kill "$process_id"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        $0 stop
        $0 start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
