#!/usr/bin/env bash
# The script manages daemons according to certain conditions

script_name="manage_my_process"
pid_file="/var/run/$script_name.pid"

start() {
    "./$script_name" &
    process_id=$!
    echo "$process_id" > "$pid_file"
    echo "$script_name started"
}

stop() {
    if [ -e "$pid_file" ]; then
        process_id=$(cat "$pid_file")
        kill "$process_id"
        rm "$pid_file"
        echo "$script_name stopped"
    else
        echo "$script_name is not running"
    fi
}

restart() {
    stop
    start
    echo "$script_name restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
